### ISSUE TITLE
我实现的跟你差不多，没有用type参数，直接用的第一级路由

### ISSUE THREAD

**Issue by tristonej** [yvanwangl/AntMobileDemo#1]
const path = props.location.pathname.split('/')[1];

      <TabBar.Item
        title="订单"
        key="order"
        icon ={< Icon type = {require('../svg/home.svg')} size = "md" />}
        selectedIcon={< Icon type = {require('../svg/email.svg')} size = "md" />}
        selected={path === 'order'}
        onPress={() => {
        props.dispatch(routerRedux.push('/order'));
      }}
        >
       { path === 'order'? props.children:null }

      </TabBar.Item>

**Comment by yvanwangl** [comment]
@tristonej 今天才发现这个项目有个issue，老铁 666 ，咱们心有灵犀啊 👍
